In [4]:
from PIL import Image
import numpy as np
import math


i1=Image.open('kuaui_hawaii.tiff')
iar=np.asarray(i1)
iar.setflags(write=1)
print (iar.shape)



(8192, 8192, 3)


In [5]:
coast= []
for m in range(3351,3356):
    for n in range(2107,2117):
        coast.append(iar[m][n])
print (len(coast))

    

50


In [6]:
field= []
for m in range(1425,1430):
    for n in range(7065,7075):
        field.append(iar[m][n])
print (len(field))

50


In [7]:
water= []
for m in range(6248,6253):
    for n in range(404,414):
        water.append(iar[m][n])
        
print (water[9])


[59 66 81]


In [8]:
house= []
for m in range(3620,3630):
    for n in range(3089,3094):
        house.append(iar[m][n])
        
print (len(house))


50


In [9]:
road= []
for m in range(3367,3372):
    for n in range(4387,4397):
        road.append(iar[m][n])
        
print(road[5])

[112 119 111]


In [10]:
forest= []
for m in range(1052,1057):
    for n in range(3876,3886):
        forest.append(iar[m][n])
        
print(forest[5])

[ 74 102  87]


In [11]:
building= []
for m in range(2023,2028):
    for n in range(268,278):
        building.append(iar[m][n])
        
print(building[5])

[196 204 209]


In [12]:
from math import exp
def gaussian(x,m,d):
    val=[1,1,1]    
    fc=((1/(2*3.14*d*d)*np.exp((-0.5)*((x-m)/d)**2)))
    val=(val*fc)
    v2=1
    for i in range(3):
        v2=v2*fc[i]
    return v2

a=[6,2,7]
b=[6,2,8]
c=[7,3,8]

npa=np.array(a)
npb=np.array(b)
npc=np.array(c)
d=gaussian(npa,npb,npc)
print(d)

1.4194156186e-07


In [13]:
import math
def clsmean(cls):
    val=[0,0,0]
    for eachpix in cls:
        val+=eachpix
    return(val/len(cls))
def clsdev(cls):
    val=[0,0,0]
    meanval=clsmean(cls)
   
    for eachpix in cls:
        val+=(eachpix-meanval)**2
    
    le=len(cls)
    val2=[0,0,0]
    
    val2+=val/le
    dev=[0,0,0]
    
    dev+=np.sqrt(val2)
        
    return dev

cdev=clsdev(coast)
print(cdev)


[ 2.41503623  2.65329983  3.28785644]


In [14]:
def maxpos(ar):
    max=0
    for i in range(len(ar)):
        if (ar[i]>max):
            max=ar[i]
            position=i
            
    return position
        
        
        

In [65]:
classes=[field,coast,water,house,road,forest,building]
devarray=[clsdev(eachclass) for eachclass in classes]
meanarray=[clsmean(eachclass) for eachclass in classes]
sumofclasses=sum(len(eachclass) for eachclass in classes)
pocarray=[(len(eachclass)/sumofclasses) for eachclass in classes]
def classifpix(pix,k):
    sum=0
    for i in range(len(devarray)):
        sum+=((pocarray[i])*gaussian(pix,meanarray[i],devarray[i]))
    val=(pocarray[k]*gaussian(pix,meanarray[k],devarray[k]))/sum
    return val

              
def predictclass(pix):
    index=None
    maxprob=0
    for i in range(len(devarray)):
        gp=classifpix(pix,i)
        if (gp>maxprob):
            maxprob=gp
            index=i
    return index
        

testpix=[176,76,77]        
for i in range(len(devarray)):
    print(classifpix(testpix,i))

              


    
    
    
    
    
        
        
    

1.53076120554e-65
0.0
0.0
1.0
0.0
5.09355123616e-15
0.0


In [16]:
def mapclassify(pix):
    probarray=[]
    for eachclass in classes:
        val=classifpix(pix,eachclass)
        probarray.append(val)
    classno=np.argmax(probarray)
    return classno


In [17]:
array=[6,2,7,8,5,8,5,14]
pos=np.argmax(array)
print(pos)

7


In [18]:
import time

In [19]:
##### 

In [18]:
i=0
t1=time.time()
for eachrow in iar:
    for eachpix in eachrow:
        classify(eachpix)
        if (i%100==0):
            print (i)
            
            print(time.time()-t1)
        i+=1
        
        
        

0
0.026334524154663086
100
0.9732034206390381
200
2.133729934692383
300
3.4165377616882324
400
4.902677297592163
500
6.580382585525513
600
8.436372518539429
700
10.481488466262817
800
12.704776525497437
900
15.18068528175354
1000
17.8224937915802
1100
20.686110258102417
1200
23.675729513168335
1300
26.811674118041992
1400
30.119832754135132
1500
33.61217164993286
1600
37.29497838020325
1700
41.271726846694946
1800
45.376089572906494
1900
49.767781496047974
2000
54.281787157058716
2100
58.94769501686096
2200
63.80420398712158
2300
68.85707402229309
2400
74.0788221359253
2500
79.43335390090942
2600
85.09088706970215
2700
90.9864091873169
2800
97.04964184761047
2900
103.2800657749176
3000
109.75793838500977
3100
116.386554479599
3200
123.18633508682251
3300
130.08727049827576
3400
137.25505328178406
3500
144.4747326374054
3600
151.8636224269867
3700
159.5083749294281
3800
167.48589706420898
3900
175.5741732120514
4000
183.9582211971283
4100
192.3680238723755
4200
200.9254515171051


KeyboardInterrupt: 

In [20]:
a = np.array([1, 2, 3])
classify(a)

In [24]:
import cv2
filename = "kuaui_hawaii.tiff"
oriimage = cv2.imread(filename)

newimage = cv2.resize(oriimage,(720,720))
cv2.imshow("original image",oriimage)
cv2.imwrite("khsmall.png",newimage)


True

In [26]:
i2=Image.open('khsmall.png')
iar2=np.asarray(i2)
iar2.setflags(write=1)
print (iar2.shape)


(720, 720, 3)


In [29]:
i3=Image.open('khsmall2.png')
iar3=np.asarray(i3)
iar3.setflags(write=1)
print (iar3.shape)

(256, 256, 3)


In [67]:
fieldn=0
coastn=0
watern=0
housen=0
roadn=0
forestn=0
buildingn=0
j=0
t1=time.time()
for eachrow in iar2:
    for eachpix in eachrow:
        if(predictclass(eachpix)==0):
            fieldn+=1
        if(predictclass(eachpix)==1):
            coastn+=1
        if(predictclass(eachpix)==2):
            watern+=1
        if(predictclass(eachpix)==3):
            housen+=1
        if(predictclass(eachpix)==4):
            roadn+=1
        if(predictclass(eachpix)==5):
            forestn+=1
        if(predictclass(eachpix)==6):
            buildingn+=1
        
        
    
        if (j%100==0):
            print (j)
            
            print(time.time()-t1)
        j+=1
    

    

0
0.008637428283691406
100
0.4646303653717041
200
0.8939836025238037
300
1.350905179977417
400
1.813535213470459
500
2.276759624481201
600
2.739964246749878
700
3.2002077102661133
800
3.6631617546081543
900
4.121459007263184
1000
4.584433555603027
1100
5.0155439376831055
1200
5.427181720733643
1300
5.875442266464233
1400
6.341010808944702
1500
6.7938525676727295
1600
7.249640703201294
1700
7.7106873989105225
1800
8.13974118232727
1900
8.595525979995728
2000
9.045329809188843
2100
9.478960752487183
2200
9.939134120941162
2300
10.361612558364868
2400
10.827110528945923
2500
11.288007020950317
2600
11.727824926376343
2700
12.192789077758789
2800
12.662899732589722
2900
13.12774920463562
3000
13.588042974472046
3100
14.023378849029541
3200
14.48197627067566
3300
14.941405773162842
3400
15.401500940322876
3500
15.860390901565552
3600
16.32109498977661
3700
16.776089191436768
3800
17.246610641479492
3900
17.792782068252563
4000
18.255470514297485
4100
18.713679552078247
4200
19.1713745594024

34200
157.25646901130676
34300
157.727392911911
34400
158.19596076011658
34500
158.6356496810913
34600
159.1005232334137
34700
159.5674765110016
34800
160.02942609786987
34900
160.50004315376282
35000
160.9262764453888
35100
161.3857696056366
35200
161.85027813911438
35300
162.31770420074463
35400
162.7817986011505
35500
163.24671459197998
35600
163.70041871070862
35700
164.16687035560608
35800
164.61992526054382
35900
165.08379936218262
36000
165.545893907547
36100
166.00953936576843
36200
166.4762020111084
36300
166.91297912597656
36400
167.3236563205719
36500
167.77318954467773
36600
168.23590970039368
36700
168.70646977424622
36800
169.17230820655823
36900
169.64120054244995
37000
170.1035602092743
37100
170.5577163696289
37200
171.01316380500793
37300
171.4809696674347
37400
171.95727634429932
37500
172.44978976249695
37600
172.92111706733704
37700
173.38681149482727
37800
173.85217332839966
37900
174.29500222206116
38000
174.76709079742432
38100
175.23334169387817
38200
175.69378

67500
309.66653990745544
67600
310.1277403831482
67700
310.5915296077728
67800
311.0527768135071
67900
311.5232472419739
68000
311.99367237091064
68100
312.4245138168335
68200
312.8881151676178
68300
313.35686016082764
68400
313.82530903816223
68500
314.2583990097046
68600
314.6934003829956
68700
315.15153527259827
68800
315.6185519695282
68900
316.0793836116791
69000
316.52786684036255
69100
316.9824209213257
69200
317.45096945762634
69300
317.88195753097534
69400
318.3429880142212
69500
318.80412125587463
69600
319.28364300727844
69700
319.7760326862335
69800
320.2469108104706
69900
320.69275546073914
70000
321.16531467437744
70100
321.60411310195923
70200
322.0703537464142
70300
322.5323464870453
70400
323.0000922679901
70500
323.4456744194031
70600
323.87974786758423
70700
324.3474016189575
70800
324.8086955547333
70900
325.26847290992737
71000
325.6987373828888
71100
326.09392189979553
71200
326.527245759964
71300
326.99730372428894
71400
327.42618012428284
71500
327.8679964542389

101400
464.4320960044861
101500
464.8976147174835
101600
465.3713080883026
101700
465.8655574321747
101800
466.32947039604187
101900
466.7690954208374
102000
467.2126717567444
102100
467.6722435951233
102200
468.1326744556427
102300
468.5672824382782
102400
468.99337792396545
102500
469.444855928421
102600
469.910489320755
102700
470.3751893043518
102800
470.8213474750519
102900
471.27547812461853
103000
471.6783730983734
103100
472.117662191391
103200
472.5551941394806
103300
472.9396553039551
103400
473.4060957431793
103500
473.87793350219727
103600
474.3455345630646
103700
474.813761472702
103800
475.2792673110962
103900
475.7432746887207
104000
476.2038242816925
104100
476.66627407073975
104200
477.12204575538635
104300
477.5809190273285
104400
478.01717376708984
104500
478.48014211654663
104600
478.9465956687927
104700
479.4075720310211
104800
479.86434674263
104900
480.32833909988403
105000
480.78329586982727
105100
481.2438123226166
105200
481.7056231498718
105300
482.1650071144

134200
614.208048582077
134300
614.6680035591125
134400
615.1274316310883
134500
615.5865445137024
134600
616.0035176277161
134700
616.4667618274689
134800
616.9345874786377
134900
617.3976202011108
135000
617.8595843315125
135100
618.3269200325012
135200
618.7919545173645
135300
619.2545688152313
135400
619.7162506580353
135500
620.1791095733643
135600
620.6451146602631
135700
621.1145887374878
135800
621.5343458652496
135900
621.9953680038452
136000
622.4367506504059
136100
622.9025559425354
136200
623.4365499019623
136300
623.8982598781586
136400
624.3546886444092
136500
624.8177223205566
136600
625.2738614082336
136700
625.7254912853241
136800
626.184648513794
136900
626.6462807655334
137000
627.1079685688019
137100
627.5493321418762
137200
628.0087504386902
137300
628.4620151519775
137400
628.9221234321594
137500
629.3861150741577
137600
629.8429889678955
137700
630.3013792037964
137800
630.7631013393402
137900
631.2259995937347
138000
631.6870529651642
138100
632.146986246109
138

763.8320603370667
167200
764.2933170795441
167300
764.752507686615
167400
765.214949131012
167500
765.6738066673279
167600
766.144031047821
167700
766.5966238975525
167800
767.0540781021118
167900
767.5150547027588
168000
767.9766683578491
168100
768.4402358531952
168200
768.8923466205597
168300
769.3589951992035
168400
769.8245267868042
168500
770.2626123428345
168600
770.7295589447021
168700
771.1890907287598
168800
771.6561653614044
168900
772.1211082935333
169000
772.5520575046539
169100
773.0145072937012
169200
773.4750440120697
169300
773.9060549736023
169400
774.3629384040833
169500
774.8215019702911
169600
775.2841935157776
169700
775.7465987205505
169800
776.2116820812225
169900
776.6756162643433
170000
777.1204414367676
170100
777.5810699462891
170200
778.026284456253
170300
778.4898335933685
170400
778.9532449245453
170500
779.4158799648285
170600
779.8899126052856
170700
780.3101971149445
170800
780.7455055713654
170900
781.207524061203
171000
781.6355557441711
171100
782.0

200200
914.9784107208252
200300
915.4067578315735
200400
915.8657593727112
200500
916.3206703662872
200600
916.7769026756287
200700
917.2365114688873
200800
917.6963107585907
200900
918.1576180458069
201000
918.6164174079895
201100
919.0776290893555
201200
919.5233414173126
201300
919.9684321880341
201400
920.4298796653748
201500
920.8847370147705
201600
921.350873708725
201700
921.8122804164886
201800
922.231856584549
201900
922.6952660083771
202000
923.1589095592499
202100
923.6148838996887
202200
924.0333037376404
202300
924.4934320449829
202400
924.9545569419861
202500
925.3813018798828
202600
925.8569004535675
202700
926.316638469696
202800
926.7764096260071
202900
927.2393171787262
203000
927.6991395950317
203100
928.1640162467957
203200
928.6141741275787
203300
929.0727615356445
203400
929.533282995224
203500
929.9664845466614
203600
930.392582654953
203700
930.8572158813477
203800
931.2992224693298
203900
931.7579567432404
204000
932.2203605175018
204100
932.6807889938354
20420

232700
1062.8543918132782
232800
1063.3213233947754
232900
1063.753139257431
233000
1064.2195801734924
233100
1064.6809854507446
233200
1065.1435775756836
233300
1065.6052510738373
233400
1066.0655732154846
233500
1066.5338785648346
233600
1066.9942803382874
233700
1067.4730525016785
233800
1067.9357950687408
233900
1068.3737754821777
234000
1068.7992947101593
234100
1069.2206757068634
234200
1069.6448709964752
234300
1070.1111316680908
234400
1070.5832934379578
234500
1071.0538675785065
234600
1071.5163946151733
234700
1071.9422628879547
234800
1072.4030404090881
234900
1072.8648071289062
235000
1073.326738834381
235100
1073.788505077362
235200
1074.2602546215057
235300
1074.7243728637695
235400
1075.2032573223114
235500
1075.6668560504913
235600
1076.1307122707367
235700
1076.5542421340942
235800
1077.0228307247162
235900
1077.4584031105042
236000
1077.9082775115967
236100
1078.3729946613312
236200
1078.799762248993
236300
1079.2648293972015
236400
1079.7442922592163
236500
1080.2030

264500
1207.1591947078705
264600
1207.6182513237
264700
1208.0781362056732
264800
1208.5348947048187
264900
1208.9747710227966
265000
1209.4321074485779
265100
1209.8905498981476
265200
1210.345939397812
265300
1210.7754409313202
265400
1211.2360289096832
265500
1211.6666855812073
265600
1212.1156961917877
265700
1212.5623233318329
265800
1213.0132865905762
265900
1213.459712266922
266000
1213.9167909622192
266100
1214.370416879654
266200
1214.826102256775
266300
1215.250597000122
266400
1215.7056713104248
266500
1216.15815782547
266600
1216.6202821731567
266700
1217.0806086063385
266800
1217.5288729667664
266900
1217.983959197998
267000
1218.4452221393585
267100
1218.9074184894562
267200
1219.3670825958252
267300
1219.8305218219757
267400
1220.2984080314636
267500
1220.7641370296478
267600
1221.1956717967987
267700
1221.6640281677246
267800
1222.1018245220184
267900
1222.568814277649
268000
1223.0375890731812
268100
1223.4998531341553
268200
1223.970463514328
268300
1224.43789601326
2

1353.0053453445435
296600
1353.452078819275
296700
1353.9026701450348
296800
1354.3502488136292
296900
1354.7992703914642
297000
1355.2109892368317
297100
1355.6588160991669
297200
1356.1190004348755
297300
1356.5885217189789
297400
1357.0131962299347
297500
1357.4656293392181
297600
1357.9162633419037
297700
1358.3452188968658
297800
1358.798369884491
297900
1359.2097668647766
298000
1359.6171250343323
298100
1360.0702209472656
298200
1360.5058255195618
298300
1360.9554769992828
298400
1361.404146194458
298500
1361.8556172847748
298600
1362.3092801570892
298700
1362.7625312805176
298800
1363.2171864509583
298900
1363.6785972118378
299000
1364.087242603302
299100
1364.5391676425934
299200
1364.9968631267548
299300
1365.4546637535095
299400
1365.8937513828278
299500
1366.3431708812714
299600
1366.8057582378387
299700
1367.2436146736145
299800
1367.704140663147
299900
1368.1465010643005
300000
1368.576046705246
300100
1368.99165558815
300200
1369.446902513504
300300
1369.9066467285156
30

328500
1498.1204867362976
328600
1498.5622775554657
328700
1499.002331495285
328800
1499.4645056724548
328900
1499.9281125068665
329000
1500.391345500946
329100
1500.8535697460175
329200
1501.2845559120178
329300
1501.7224826812744
329400
1502.1846828460693
329500
1502.6480300426483
329600
1503.1091675758362
329700
1503.5694425106049
329800
1504.0264647006989
329900
1504.4899671077728
330000
1504.9537777900696
330100
1505.3764798641205
330200
1505.8345427513123
330300
1506.2954111099243
330400
1506.7582323551178
330500
1507.2178223133087
330600
1507.6803514957428
330700
1508.1093575954437
330800
1508.5157153606415
330900
1508.9293856620789
331000
1509.3897671699524
331100
1509.809386730194
331200
1510.2269368171692
331300
1510.6820685863495
331400
1511.1383669376373
331500
1511.5685894489288
331600
1512.0213260650635
331700
1512.4571006298065
331800
1512.9118206501007
331900
1513.3223736286163
332000
1513.7796154022217
332100
1514.2401323318481
332200
1514.702026605606
332300
1515.1541

360300
1642.161690235138
360400
1642.6228611469269
360500
1643.0478641986847
360600
1643.5093445777893
360700
1643.9701294898987
360800
1644.4319994449615
360900
1644.891119480133
361000
1645.350415468216
361100
1645.8352484703064
361200
1646.297222852707
361300
1646.7605376243591
361400
1647.2232191562653
361500
1647.6883137226105
361600
1648.1538486480713
361700
1648.6167259216309
361800
1649.0815148353577
361900
1649.5430481433868
362000
1649.9972155094147
362100
1650.4699659347534
362200
1650.918020248413
362300
1651.3800332546234
362400
1651.8151078224182
362500
1652.2734851837158
362600
1652.736332654953
362700
1653.173035621643
362800
1653.6019988059998
362900
1654.01278090477
363000
1654.4764316082
363100
1654.8989341259003
363200
1655.361690044403
363300
1655.8117718696594
363400
1656.2250635623932
363500
1656.668391942978
363600
1657.1099138259888
363700
1657.5276265144348
363800
1657.9889521598816
363900
1658.4339678287506
364000
1658.8593471050262
364100
1659.3226010799408


392300
1786.7362546920776
392400
1787.1942687034607
392500
1787.6499438285828
392600
1788.1083381175995
392700
1788.5372455120087
392800
1788.9614288806915
392900
1789.420424938202
393000
1789.8817510604858
393100
1790.3377022743225
393200
1790.7976322174072
393300
1791.2147274017334
393400
1791.6743240356445
393500
1792.102966785431
393600
1792.5646300315857
393700
1793.0190451145172
393800
1793.4675266742706
393900
1793.9224936962128
394000
1794.3478257656097
394100
1794.8289165496826
394200
1795.2856287956238
394300
1795.7437770366669
394400
1796.2164425849915
394500
1796.6784913539886
394600
1797.1029751300812
394700
1797.5547311306
394800
1798.015605688095
394900
1798.4752869606018
395000
1798.9348208904266
395100
1799.3548033237457
395200
1799.8159484863281
395300
1800.2765574455261
395400
1800.699514389038
395500
1801.1605157852173
395600
1801.6228041648865
395700
1802.0784447193146
395800
1802.5255455970764
395900
1802.9790678024292
396000
1803.437510251999
396100
1803.89681100

424100
1931.3463745117188
424200
1931.778464794159
424300
1932.2024993896484
424400
1932.6651892662048
424500
1933.1352286338806
424600
1933.5862576961517
424700
1934.0038917064667
424800
1934.4751889705658
424900
1934.9386246204376
425000
1935.4009647369385
425100
1935.8430345058441
425200
1936.2605566978455
425300
1936.6879374980927
425400
1937.1519422531128
425500
1937.59290766716
425600
1938.0297503471375
425700
1938.4943017959595
425800
1938.9587643146515
425900
1939.4228949546814
426000
1939.8579759597778
426100
1940.311235666275
426200
1940.7563858032227
426300
1941.216878414154
426400
1941.6778106689453
426500
1942.138664484024
426600
1942.5843334197998
426700
1943.0108380317688
426800
1943.4717772006989
426900
1943.915964126587
427000
1944.3770411014557
427100
1944.8388965129852
427200
1945.300456047058
427300
1945.762220621109
427400
1946.2354583740234
427500
1946.6957199573517
427600
1947.1764857769012
427700
1947.6404268741608
427800
1948.06982588768
427900
1948.51442670822

456000
2076.6603343486786
456100
2077.1214447021484
456200
2077.58017206192
456300
2078.00230717659
456400
2078.461837530136
456500
2078.92129445076
456600
2079.378821372986
456700
2079.836664199829
456800
2080.299485206604
456900
2080.7594163417816
457000
2081.2149732112885
457100
2081.6667935848236
457200
2082.1217048168182
457300
2082.571220636368
457400
2083.020672082901
457500
2083.472708463669
457600
2083.9220571517944
457700
2084.372671365738
457800
2084.7976825237274
457900
2085.2560205459595
458000
2085.715444803238
458100
2086.1754858493805
458200
2086.634007692337
458300
2087.079320907593
458400
2087.5256378650665
458500
2088.0383365154266
458600
2088.4938414096832
458700
2088.941734313965
458800
2089.4163110256195
458900
2089.873958826065
459000
2090.280261039734
459100
2090.7288930416107
459200
2091.18048620224
459300
2091.6294128894806
459400
2092.0767402648926
459500
2092.5239832401276
459600
2092.9409782886505
459700
2093.400946855545
459800
2093.857182264328
459900
209

488200
2221.794548034668
488300
2222.2515387535095
488400
2222.6687195301056
488500
2223.10804104805
488600
2223.557466983795
488700
2224.007903575897
488800
2224.459485769272
488900
2224.9092462062836
489000
2225.3186888694763
489100
2225.7656807899475
489200
2226.2221009731293
489300
2226.6796197891235
489400
2227.1380608081818
489500
2227.5940475463867
489600
2228.052405357361
489700
2228.532157421112
489800
2228.988306283951
489900
2229.4440517425537
490000
2229.9047265052795
490100
2230.363165140152
490200
2230.820739507675
490300
2231.2526473999023
490400
2231.6847388744354
490500
2232.1451437473297
490600
2232.5848507881165
490700
2233.0432999134064
490800
2233.462942838669
490900
2233.925551176071
491000
2234.3912196159363
491100
2234.850804567337
491200
2235.3149087429047
491300
2235.769748687744
491400
2236.2286083698273
491500
2236.686751127243
491600
2237.1445949077606
491700
2237.5900044441223
491800
2238.0490930080414
491900
2238.536004781723
492000
2238.9938926696777
492

In [68]:
print(forestn)

239240


In [70]:
classsum=518400
perforest=forestn/classsum*100
perwater=watern/classsum*100
perroad=roadn/classsum*100
perfield=fieldn/classsum*100
percoast=coastn/classsum*100
perbuilding=buildingn/classsum*100
perhouse=housen/classsum*100

In [71]:
print ('% of forest in image is',perforest)
print ('% of field in image is',perfield)
print ('% of road in image is',perroad)
print ('% of house in image is',perhouse)
print ('% of water in image is',perwater)
print ('% of coast in image is',percoast)
print ('% of building in image is',perbuilding)


% of forest in image is 46.14969135802469
% of field in image is 8.16724537037037
% of road in image is 10.753472222222223
% of house in image is 2.181327160493827
% of water in image is 32.367283950617285
% of coast in image is 0.16608796296296297
% of building in image is 0.21489197530864196


In [73]:
fieldmap=np.array([165, 191, 126])
coastmap=np.array([232, 224, 178])
watermap=np.array([30, 48, 206])
housemap=np.array([191, 43, 26])
roadmap=np.array([122, 115, 115])
forestmap=np.array([19, 66, 32])
buildingmap=np.array([129, 130, 110])
maparray=np.zeros([720,720,3])
for i in range(720):
    for j in range(720):
        getclass=predictclass(iar2[i][j])
        if (getclass==0):
            maparray[i][j]+=fieldmap
        elif (getclass==1):
            maparray[i][j]+=coastmap
        elif (getclass==3):
            maparray[i][j]+=watermap
        elif (getclass==2):
            maparray[i][j]+=housemap
        elif (getclass==4):
            maparray[i][j]+=roadmap
        elif (getclass==5):
            maparray[i][j]+=forestmap
        elif (getclass==6):
            maparray[i][j]+=buildingmap
    print(i) 
            

        
            
            
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [74]:
cv2.imwrite("map.png",maparray)

True

In [128]:
print(maparray[111][111])
print(maparray[50][57])
print(maparray[127][31])


[ 19.  66.  32.]
[ 122.  115.  115.]
[ 19.  66.  32.]


4


[165, 191, 126]


[ 19.  66.  32.]
