In [1]:
from PIL import Image
import numpy as np
import math
import cv2
import time







In [2]:
i=Image.open('kuaui_hawaii.tiff')
i1=Image.open("khsmall.png")
iar=np.asarray(i)
iar1=np.asarray(i1)
print(iar1.shape)




(720, 720, 3)


In [67]:
import copy 
trainingset=[]
for i in range(3351,3356):
    for j in range(2107,2117):
        n=iar[i][j]
        nx=np.append(n,0)
        trainingset.append(nx)
for i in range(1425,1430):
    for j in range(7065,7075):
        n=iar[i][j]
        nx=np.append(n,1)
        trainingset.append(nx)
for i in range(6248,6253):
    for j in range(404,414):
        n=iar[i][j]
        nx=np.append(n,2)
        trainingset.append(nx)
for i in range(3620,3630):
    for j in range(3089,3094):
        n=iar[i][j]
        nx=np.append(n,3)
        trainingset.append(nx)
for i in range(3367,3372):
    for j in range(4387,4397):
        n=iar[i][j]
        nx=np.append(n,4)
        trainingset.append(nx)
for i in range(1052,1057):
    for j in range(3876,3886):
        n=iar[i][j]
        nx=np.append(n,5)
        trainingset.append(nx)
for i in range(2023,2028):
    for j in range(268,278):
        n=iar[i][j]
        nx=np.append(n,6)
        trainingset.append(nx)

print(len(trainingset))
for row in trainingset:
    print (row)

       
    


350
[234 224 211   0]
[237 228 217   0]
[235 227 215   0]
[233 224 211   0]
[237 228 217   0]
[233 224 211   0]
[235 225 213   0]
[240 232 221   0]
[235 225 213   0]
[235 225 213   0]
[235 225 213   0]
[237 227 216   0]
[237 227 216   0]
[233 224 211   0]
[234 225 213   0]
[235 225 213   0]
[234 224 212   0]
[235 226 215   0]
[237 227 216   0]
[234 224 212   0]
[239 228 217   0]
[232 222 207   0]
[234 225 212   0]
[239 230 219   0]
[237 227 216   0]
[235 225 213   0]
[232 221 208   0]
[232 222 209   0]
[239 230 217   0]
[237 226 215   0]
[237 228 217   0]
[235 225 213   0]
[239 228 217   0]
[240 231 219   0]
[235 226 215   0]
[234 225 213   0]
[235 226 215   0]
[232 222 209   0]
[231 220 207   0]
[234 225 213   0]
[237 227 215   0]
[237 226 215   0]
[239 228 217   0]
[237 227 215   0]
[240 231 219   0]
[239 230 219   0]
[237 227 216   0]
[239 230 217   0]
[237 225 215   0]
[232 221 207   0]
[132 116 101   1]
[135 121 107   1]
[132 119 101   1]
[132 116  97   1]
[132 116  91   1]
[132 1

In [135]:
from math import log
def testsplit(index,value,data):
    left=[]
    right=[]
    for row in data:
        if (row[index]>value):
            right.append(row)
            
            
        else:
            left.append(row)
            
    groups=[left,right]
    return groups
def giniindex(groups,classes):
    te=0
    
    for group in groups:
        score=1
        size=len(group)
        
        for classval in classes:
            
            if(size==0):
                prob=0
            else:    
                prob=[row[-1] for row in group].count(classval)/size    
            
                score=score-(prob*prob)
        te=te+score
    return te


def createsplit(data):
    bestgini=9999
    classes=[0,1,2,3,4,5,6]
    bestindex=None
    bestval=None
    
    
    for row in data:
        
            
            
        
        for i in range(0,len(row)-1):
            groups=testsplit(i,row[i],data)
            gn=giniindex(groups,classes)
            
            if(gn<bestgini):
                bestindex=i
                bestval=row[i]
                bestgini=gn
                print('value is ',bestgini,'at ',bestindex,'and ',bestval)
                
                
    bestsplit=testsplit(bestindex,bestval,data)
    node={'groups':bestsplit,'index':bestindex,'value':bestval}
    
    
    return node
    


            
        

In [45]:
def to_terminal(group):
    outcomes = [row[-1] for row in group]
    return max(set(outcomes), key=outcomes.count)

In [46]:
def split(node, max_depth, min_size, depth):
    left, right = node['groups'] 
    print('left = ',left)
    print('right =',right)
    del(node['groups'])
    if not left or not right:
        node['left'] = node['right'] = to_terminal(left + right)
        return
    
    if depth >= max_depth:
        print('depth exceeded')
        node['left'], node['right'] = to_terminal(left), to_terminal(right)
        return
    if len(left) <= min_size:
        print('left size small')
        node['left'] = to_terminal(left)
    else:
        node['left'] = createsplit(left)
        
        split(node['left'], max_depth, min_size, depth+1)
        
    if len(right) <= min_size:
        print('right size small')
        node['right'] = to_terminal(right)
    else:
        node['right'] = createsplit(right)
        
        split(node['right'], max_depth, min_size, depth+1)

In [117]:
def predict(node, row):
    if row[node['index']] <= node['value']:
        if isinstance(node['left'], dict):
            return predict(node['left'], row)
        else:
            return node['left']
    else:
        if isinstance(node['right'], dict):
            return predict(node['right'], row)
        else:
            return node['right']

In [48]:
def build_tree(train, max_depth, min_size):
    root = createsplit(train)
    
    split(root, max_depth, min_size, 0)
    return root



In [136]:
tre=build_tree(trainingset,6,5)
print(tre)



value is  0.8472199967953855 at  0 and  234
value is  0.8444280078895466 at  1 and  224
value is  0.8428720083246616 at  2 and  211
value is  0.8420523454928206 at  0 and  233
value is  0.839420735614507 at  0 and  232
value is  0.8365192954939056 at  1 and  221
value is  0.8344278760720082 at  0 and  231
value is  0.8333333333333333 at  0 and  219
value is  1.3764890353866244 at  0 and  132
value is  1.3757332765316461 at  0 and  135
value is  1.356897474892937 at  2 and  97
value is  1.3158676392042594 at  2 and  91
value is  1.2755666964135406 at  2 and  119
value is  1.2149871270813701 at  2 and  123
value is  1.1316055462521613 at  2 and  132
value is  1.0763888888888888 at  2 and  137
value is  1.0369378711956823 at  0 and  59
value is  0.9489984227846755 at  1 and  71
value is  0.8333240120356596 at  1 and  59
value is  0.8331811541271003 at  0 and  212
value is  0.8327078251079 at  0 and  209
value is  0.8318865740740741 at  0 and  204
value is  0.7999999999999998 at  2 and  17

5


In [14]:
smalltrain=[]
for i in range(150,155):
    for j in range(348,353):
        n=iar1[i][j]
        nx=np.append(n,0)
        smalltrain.append(nx)
for i in range(601,606):
    for j in range(255,260):
        n=iar1[i][j]
        nx=np.append(n,1)
        smalltrain.append(nx)
for i in range(49,54):
    for j in range(665,670):
        n=iar1[i][j]
        nx=np.append(n,2)
        smalltrain.append(nx)
for i in range(339,344):
    for j in range(332,337):
        n=iar1[i][j]
        nx=np.append(n,3)
        smalltrain.append(nx)
print(len(smalltrain))


100


In [83]:
dectree2=build_tree(smalltrain,3,20)
print(dectree2)

bestentropy is  0  at  0  and  83
val is  83 and index is 0
bestentropy is  0  at  0  and  83
val is  83 and index is 0
bestentropy is  0  at  0  and  97
val is  97 and index is 0
bestentropy is  0  at  0  and  120
val is  120 and index is 0
bestentropy is  0  at  0  and  122
val is  122 and index is 0
{'index': 0, 'value': 83, 'left': {'index': 0, 'value': 83, 'left': 1, 'right': 1}, 'right': {'index': 0, 'value': 97, 'left': 0, 'right': {'index': 0, 'value': 120, 'left': 2, 'right': {'index': 0, 'value': 122, 'left': 2, 'right': 3}}}}


In [16]:
testrow=[112,241,221]
b=predict(dectree2,testrow)
b

2

[[1 2]
 [3 4]
 [5 6]]


In [127]:
coastn=0
fieldn=0
watern=0
housen=0
roadn=0
forestn=0
buildingn=0
j=0
t1=time.time()
for row in iar1:
    for pix in row:
        if(j%100==0):
            print(j)
            print(time.time()-t1)
        j=j+1
        if(predict(tre,pix)==0):
            coastn=coastn+1
        if(predict(tre,pix)==1):
            fieldn=fieldn+1
        if(predict(tre,pix)==2):
            watern=watern+1
        if(predict(tre,pix)==3):
            housen=housen+1
        if(predict(tre,pix)==4):
            roadn=roadn+1
        if(predict(tre,pix)==5):
            forestn=forestn+1
        if(predict(tre,pix)==6):
            buildingn=buildingn+1

0
0.0006265640258789062
100
0.010701417922973633
200
0.02001023292541504
300
0.026073455810546875
400
0.0318760871887207
500
0.037435293197631836
600
0.04284191131591797
700
0.048267364501953125
800
0.05376029014587402
900
0.05941152572631836
1000
0.06509542465209961
1100
0.07066178321838379
1200
0.07623982429504395
1300
0.08179569244384766
1400
0.08715939521789551
1500
0.09259533882141113
1600
0.09812045097351074
1700
0.10369372367858887
1800
0.10928964614868164
1900
0.11473345756530762
2000
0.1201639175415039
2100
0.12541842460632324
2200
0.1307051181793213
2300
0.13614249229431152
2400
0.14159083366394043
2500
0.1470167636871338
2600
0.15245389938354492
2700
0.15786242485046387
2800
0.16315007209777832
2900
0.16822338104248047
3000
0.17370843887329102
3100
0.1791062355041504
3200
0.18452167510986328
3300
0.1899416446685791
3400
0.19533014297485352
3500
0.2005782127380371
3600
0.20564842224121094
3700
0.21131348609924316
3800
0.21680140495300293
3900
0.2225341796875
4000
0.2282373905

2.004295587539673
35200
2.0098814964294434
35300
2.015512228012085
35400
2.021395444869995
35500
2.02697491645813
35600
2.0331218242645264
35700
2.0387349128723145
35800
2.0448904037475586
35900
2.0514705181121826
36000
2.057222843170166
36100
2.062835216522217
36200
2.0692718029022217
36300
2.0748307704925537
36400
2.080326557159424
36500
2.087352752685547
36600
2.092926263809204
36700
2.0984504222869873
36800
2.104477882385254
36900
2.10998797416687
37000
2.1156580448150635
37100
2.121232271194458
37200
2.126727342605591
37300
2.132342576980591
37400
2.137746810913086
37500
2.1433892250061035
37600
2.1491057872772217
37700
2.1547553539276123
37800
2.1603240966796875
37900
2.1658103466033936
38000
2.1713759899139404
38100
2.1768407821655273
38200
2.182476282119751
38300
2.1880717277526855
38400
2.1936872005462646
38500
2.1992690563201904
38600
2.204712152481079
38700
2.2102246284484863
38800
2.2158071994781494
38900
2.2211508750915527
39000
2.2266173362731934
39100
2.232724189758301
3

77600
4.417131423950195
77700
4.4225969314575195
77800
4.428051471710205
77900
4.433552265167236
78000
4.438941478729248
78100
4.444421768188477
78200
4.4498374462127686
78300
4.456416130065918
78400
4.463704586029053
78500
4.469799041748047
78600
4.475372552871704
78700
4.4809534549713135
78800
4.486475944519043
78900
4.4920737743377686
79000
4.49765157699585
79100
4.503160715103149
79200
4.508517503738403
79300
4.513902425765991
79400
4.519301652908325
79500
4.524758338928223
79600
4.5302112102508545
79700
4.5355329513549805
79800
4.54094934463501
79900
4.546289920806885
80000
4.551690340042114
80100
4.557119131088257
80200
4.562585353851318
80300
4.567983150482178
80400
4.5733771324157715
80500
4.578761577606201
80600
4.5840935707092285
80700
4.589508056640625
80800
4.594854354858398
80900
4.600240230560303
81000
4.605675935745239
81100
4.611216306686401
81200
4.616629123687744
81300
4.622037410736084
81400
4.627537488937378
81500
4.632906198501587
81600
4.638312339782715
81700
4.64

111700
6.3237152099609375
111800
6.329307317733765
111900
6.335042715072632
112000
6.340792417526245
112100
6.346426486968994
112200
6.351963520050049
112300
6.35745644569397
112400
6.363030195236206
112500
6.368591547012329
112600
6.3740949630737305
112700
6.379603147506714
112800
6.385083198547363
112900
6.390743732452393
113000
6.396305084228516
113100
6.401822328567505
113200
6.40730881690979
113300
6.412656545639038
113400
6.418046236038208
113500
6.423440456390381
113600
6.428843259811401
113700
6.434082746505737
113800
6.439424514770508
113900
6.4447877407073975
114000
6.450108051300049
114100
6.455772638320923
114200
6.461329460144043
114300
6.466963768005371
114400
6.472612142562866
114500
6.478289604187012
114600
6.48379373550415
114700
6.489298343658447
114800
6.4947288036346436
114900
6.500330448150635
115000
6.50593376159668
115100
6.511368036270142
115200
6.5168821811676025
115300
6.522290945053101
115400
6.527798175811768
115500
6.5331056118011475
115600
6.53858351707458

9.352139711380005
165600
9.357691526412964
165700
9.363290071487427
165800
9.368953466415405
165900
9.374486446380615
166000
9.380131244659424
166100
9.386288166046143
166200
9.391979455947876
166300
9.397531986236572
166400
9.403404712677002
166500
9.409142017364502
166600
9.414810419082642
166700
9.420448780059814
166800
9.426039218902588
166900
9.431757926940918
167000
9.437371969223022
167100
9.443233728408813
167200
9.448921918869019
167300
9.454607725143433
167400
9.46016526222229
167500
9.465861797332764
167600
9.471505165100098
167700
9.477089643478394
167800
9.482707262039185
167900
9.488346576690674
168000
9.493901014328003
168100
9.499411821365356
168200
9.505011320114136
168300
9.510504007339478
168400
9.515944719314575
168500
9.521434783935547
168600
9.526976585388184
168700
9.532440900802612
168800
9.53787350654602
168900
9.543299436569214
169000
9.548837661743164
169100
9.554277420043945
169200
9.559751987457275
169300
9.565277814865112
169400
9.57076382637024
169500
9.5

206100
11.634511232376099
206200
11.639798402786255
206300
11.645050764083862
206400
11.650413990020752
206500
11.6558678150177
206600
11.661234855651855
206700
11.666659832000732
206800
11.672023057937622
206900
11.677076578140259
207000
11.682454824447632
207100
11.687882900238037
207200
11.69329309463501
207300
11.698723077774048
207400
11.704093217849731
207500
11.709467649459839
207600
11.71448016166687
207700
11.719841957092285
207800
11.725181818008423
207900
11.73059630393982
208000
11.73601770401001
208100
11.741401195526123
208200
11.746662616729736
208300
11.751757621765137
208400
11.757047176361084
208500
11.762385368347168
208600
11.767817735671997
208700
11.773136854171753
208800
11.778436422348022
208900
11.783760786056519
209000
11.788890361785889
209100
11.794017791748047
209200
11.799399375915527
209300
11.80473804473877
209400
11.810333251953125
209500
11.815843105316162
209600
11.821476697921753
209700
11.826736450195312
209800
11.832275629043579
209900
11.837749719

13.731508731842041
243000
13.73677110671997
243100
13.742137908935547
243200
13.747639656066895
243300
13.754526138305664
243400
13.759824991226196
243500
13.765917778015137
243600
13.771462440490723
243700
13.777148723602295
243800
13.782546758651733
243900
13.787915706634521
244000
13.79326319694519
244100
13.797900438308716
244200
13.803306102752686
244300
13.808590650558472
244400
13.813937425613403
244500
13.819447994232178
244600
13.824884414672852
244700
13.830253839492798
244800
13.835018396377563
244900
13.84044361114502
245000
13.84572148323059
245100
13.851125717163086
245200
13.85649847984314
245300
13.861870050430298
245400
13.867228269577026
245500
13.872045993804932
245600
13.877498149871826
245700
13.882832527160645
245800
13.888242721557617
245900
13.89359712600708
246000
13.89902639389038
246100
13.904443740844727
246200
13.909476041793823
246300
13.914801597595215
246400
13.9201078414917
246500
13.925607681274414
246600
13.93082880973816
246700
13.93631887435913
2468

279500
15.728458166122437
279600
15.733970880508423
279700
15.73935866355896
279800
15.744731903076172
279900
15.750098943710327
280000
15.755183219909668
280100
15.760677814483643
280200
15.76614785194397
280300
15.771538019180298
280400
15.776931762695312
280500
15.782460689544678
280600
15.787714719772339
280700
15.792912244796753
280800
15.798365354537964
280900
15.80377721786499
281000
15.809191703796387
281100
15.81463360786438
281200
15.82008171081543
281300
15.825421333312988
281400
15.83081865310669
281500
15.83613133430481
281600
15.841650485992432
281700
15.847113847732544
281800
15.852499008178711
281900
15.857945919036865
282000
15.863372564315796
282100
15.868673324584961
282200
15.873871326446533
282300
15.879371643066406
282400
15.884847402572632
282500
15.890400886535645
282600
15.895974397659302
282700
15.90135645866394
282800
15.906602144241333
282900
15.91208291053772
283000
15.917527914047241
283100
15.92308235168457
283200
15.92864727973938
283300
15.9342067241668

331400
18.641483545303345
331500
18.646962642669678
331600
18.652361392974854
331700
18.657785654067993
331800
18.663148403167725
331900
18.66851234436035
332000
18.673906087875366
332100
18.679370641708374
332200
18.68472170829773
332300
18.690105676651
332400
18.69546914100647
332500
18.700815200805664
332600
18.706292152404785
332700
18.711770057678223
332800
18.717097282409668
332900
18.722483158111572
333000
18.72789216041565
333100
18.733253479003906
333200
18.738540172576904
333300
18.74381732940674
333400
18.749176740646362
333500
18.754552841186523
333600
18.75995707511902
333700
18.765353679656982
333800
18.77081322669983
333900
18.776060819625854
334000
18.78141951560974
334100
18.7868230342865
334200
18.792677879333496
334300
18.79834794998169
334400
18.803892135620117
334500
18.809399843215942
334600
18.814906358718872
334700
18.8201687335968
334800
18.825733423233032
334900
18.831270456314087
335000
18.83672070503235
335100
18.842138051986694
335200
18.847537755966187
335

372400
20.877017974853516
372500
20.882447481155396
372600
20.887845993041992
372700
20.893234252929688
372800
20.89869737625122
372900
20.90413808822632
373000
20.909530639648438
373100
20.914884567260742
373200
20.92030119895935
373300
20.92570424079895
373400
20.931175231933594
373500
20.936579704284668
373600
20.942178964614868
373700
20.94759774208069
373800
20.953006982803345
373900
20.95846390724182
374000
20.963870763778687
374100
20.969308376312256
374200
20.97475814819336
374300
20.980166912078857
374400
20.985515594482422
374500
20.990901470184326
374600
20.996326684951782
374700
21.001856803894043
374800
21.007288694381714
374900
21.01267409324646
375000
21.01806402206421
375100
21.023432731628418
375200
21.02884864807129
375300
21.034168481826782
375400
21.039526224136353
375500
21.04487180709839
375600
21.050251483917236
375700
21.055760145187378
375800
21.061217069625854
375900
21.06670379638672
376000
21.07260274887085
376100
21.078283309936523
376200
21.0838725566864
3

416900
23.295533418655396
417000
23.30105996131897
417100
23.30658197402954
417200
23.312114000320435
417300
23.31761860847473
417400
23.323030710220337
417500
23.32842993736267
417600
23.333797454833984
417700
23.339231252670288
417800
23.344608068466187
417900
23.349982738494873
418000
23.35539722442627
418100
23.36078929901123
418200
23.36615538597107
418300
23.371589422225952
418400
23.377020597457886
418500
23.383365154266357
418600
23.388774871826172
418700
23.394293546676636
418800
23.399760007858276
418900
23.405207633972168
419000
23.410633325576782
419100
23.416327953338623
419200
23.421730756759644
419300
23.427143573760986
419400
23.432525396347046
419500
23.437922954559326
419600
23.44325852394104
419700
23.448665618896484
419800
23.454146146774292
419900
23.459529876708984
420000
23.464934825897217
420100
23.470345735549927
420200
23.475741624832153
420300
23.48114800453186
420400
23.4865562915802
420500
23.491986989974976
420600
23.497494220733643
420700
23.5029189586639

25.940069913864136
465100
25.945465803146362
465200
25.950822830200195
465300
25.95624041557312
465400
25.96173858642578
465500
25.967134475708008
465600
25.972633600234985
465700
25.97817897796631
465800
25.983543395996094
465900
25.98892116546631
466000
25.994300842285156
466100
25.99965238571167
466200
26.00510573387146
466300
26.010443687438965
466400
26.01579713821411
466500
26.02116060256958
466600
26.02655029296875
466700
26.031906604766846
466800
26.039026260375977
466900
26.04450297355652
467000
26.049980878829956
467100
26.055412530899048
467200
26.060882329940796
467300
26.066390991210938
467400
26.07187271118164
467500
26.0786395072937
467600
26.08430504798889
467700
26.0897274017334
467800
26.095104932785034
467900
26.10057234764099
468000
26.10598087310791
468100
26.111450672149658
468200
26.11684799194336
468300
26.12219548225403
468400
26.12757182121277
468500
26.13293147087097
468600
26.138306379318237
468700
26.143770694732666
468800
26.149203777313232
468900
26.15459

In [129]:
sum=coastn+fieldn+watern+housen+roadn+forestn+buildingn
print ('% of forest in image is',forestn*100/sum)
print ('% of field in image is',fieldn*100/sum)
print ('% of road in image is',roadn*100/sum)
print ('% of house in image is',housen*100/sum)
print ('% of water in image is',watern*100/sum)
print ('% of coast in image is',coastn*100/sum)
print ('% of building in image is',buildingn*100/sum)

% of forest in image is 40.2554012345679
% of field in image is 6.637924382716049
% of road in image is 19.198109567901234
% of house in image is 1.0686728395061729
% of water in image is 31.653163580246915
% of coast in image is 0.2775848765432099
% of building in image is 0.9091435185185185


In [138]:
fieldmap=np.array([165, 191, 126])
coastmap=np.array([232, 224, 178])
watermap=np.array([30, 48, 206])
housemap=np.array([191, 43, 26])
roadmap=np.array([122, 115, 115])
forestmap=np.array([19, 66, 32])
buildingmap=np.array([129, 130, 110])
maparray=np.zeros([720,720,3])
for i in range(720):
    for j in range(720):
        getclass=predict(tre,iar1[i][j])
        if (getclass==0):
            maparray[i][j]+=fieldmap
        elif (getclass==1):
            maparray[i][j]+=coastmap
        elif (getclass==3):
            maparray[i][j]+=watermap
        elif (getclass==2):
            maparray[i][j]+=housemap
        elif (getclass==4):
            maparray[i][j]+=roadmap
        elif (getclass==5):
            maparray[i][j]+=forestmap
        elif (getclass==6):
            maparray[i][j]+=buildingmap
    print(i) 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [139]:
cv2.imwrite("map2.png",maparray)

True